name: Compilar Dylib

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instalar Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Compilar
        run: |
          make clean
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: KeyLogin.dylib
          path: .theos/obj/debug/KeyLogin.dylib
